server:
  port: 8761
  error:
    whitelabel:
      enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    healthcheck:
      enabled: true
#logging.level.com.netflix.eureka=OFF
#logging.level.com.netflix.discovery=OFF